language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build -x test"

before_deploy:
  - zip -r shkong-springboot2-webservice *
  - mkdir -p deploy
  - mv shkong-springboot2-webservice.zip deploy/shkong-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY #Travis repo settings에 설정 된 값
    secret_access_key: $AWS_SECRET_KEY #Travis repo settings 에 설정 된 값
    bucket: springboot-build-s3-burket
    region: ap-northeast-1
    skip_cleanup: true
    acl: private #zip 파일 접근을 private 으로
    local_dir: deploy # before_deploy 에서 생성한 디렉토리
    wait-until-deployed: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY #Travis repo settings에 설정 된 값
    secret_access_key: $AWS_SECRET_KEY #Travis repo settings 에 설정 된 값
    bucket: springboot-build-s3-burket
    key: shkong-springboot2-webservice.zip
    bundle_type: zip
    application: springboot-webservice
    deployment_group: springboot-webservice-group
    region: ap-northeast-1
    wait-until-deployed: true

before_install:
  - chmod +x gradlew

#CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - hanmaildatnet@hanmail.net